### ISSUE TITLE
evaluate a result for ontology alignment based on instances

### ISSUE THREAD

**Issue by Nidhalos** [phillord/owl-api#3]
hello 
who to evaluate my result for ontology alignment based on instances with references result.
what are the different methods for the evaluation of this resalt and which ones the fastest method.
it exists only oaei company !! can I evaluate the results by myself? if yes who !

**Comment by phillord** [comment]
This is a fork, not the main repo. Also, I am not sure what you are asking but it doesn't look like a bug, feature request or otherwise.
